<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Profiles\**" />
    <EmbeddedResource Remove="Profiles\**" />
    <None Remove="Profiles\**" />
  </ItemGroup>

  <ItemGroup>
    <EditorConfigFiles Remove="E:\source\repos\TerminalChad\src\TerminalChad\.editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <None Include="E:\source\repos\TerminalChad\src\TerminalChad\.editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="YamlDotNet" Version="15.1.1" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Docs\help.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Fonts\CommitMonoNerdFontMono-Regular.otf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Fonts\ProggyCleanNerdFont-Regular.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Fonts\TerminessNerdFontMono-Regular.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="install.ps1">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
